config/routes.rb
Rails.application.routes.draw do
  get "errors/not_found"
  get "errors/internal_server_error"
  resources :posts do
    resources :comments, only: %i[create destroy update edit]
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  # Defines the root path route ("/")
  root "posts#index"

  get "profile" => "pages#profile"

  # Custom error pages
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :post

  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: {minimum: 5, maximum: 55}
  validates :body, presence: true, length: {minimum: 10}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :nullify
  has_many :posts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/blog_post_controller.rb
class BlogPostController < ApplicationController
  def index
    @blog_posts = BlogPost.all
  end

  def show
    @post = BlogPost.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post!
  before_action :set_comment!, only: %i[destroy update edit]
  before_action :authorize_user!, only: %i[destroy update]

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "Comment was successfully created."
    else
      flash[:new_comment_errors] = @comment.errors.full_messages
    end
    redirect_to post_path(@post)
  end

  def destroy
    @comment.destroy!
    redirect_to post_path(@post)
  end

  def edit
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(@comment, partial: "posts/comments/edit-form", locals: {comment: @comment})
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            @comment,
            partial: "posts/comments/comment",
            locals: {
              comment: @comment,
              notice: "Comment successfully updated."
            }
          )
        end
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            @comment,
            partial: "posts/comments/edit-form",
            locals: {
              comment: @comment
            }
          )
        end
      end
    end
  end

  private

  def set_post!
    @post = Post.find(params[:post_id])
  end

  def set_comment!
    @comment = Comment.find(params[:id])
  end

  def authorize_user!
    redirect_to posts_path, notice: "You don't have a permission to do this" unless current_user == @comment.user
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:profile]

  def profile
    @user = current_user
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :authorize_user!, only: %i[edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc).page(params[:page]).per(10)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc).page(params[:page]).per(3)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_url(@post), notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    if @post.update(post_params)
      redirect_to post_url @post, notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!
    flash[:notice] = "Post was successfully destroyed."
    redirect_to request.referer, notice: "Post was successfully destroyed."
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_user!
    redirect_to posts_path, notice: "You don't have a permission to do this" unless current_user == @post.user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_post_helper.rb
module BlogPostHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  class HTMLRenderer < Redcarpet::Render::HTML
    def header(text, header_level)
      header_level = [header_level, 3].min
      "<h#{header_level}>#{text}</h#{header_level}>"
    end
  end

  def md_to_html(text)
    renderer = HTMLRenderer.new
    markdown = Redcarpet::Markdown.new(renderer)
    markdown.render(text).html_safe
  end
end

app/views/blog_post/index.html.erb
<h1 class="text-3xl">Blog</h1>

<ul class="flex flex-col gap-2 divide-y">
  <% @blog_posts.each do |post| %>
    <li>
      <a href="<%= blog_post_path(post) %>" class="block p-2 bg-slate-300 hover:bg-slate-400 transition-colors">
        <h2><%= post.title %></h2>
        <p><%= post.body %></p>
      </a>
    </li>
  <% end %>
</ul>

app/views/blog_post/show.html.erb
<h1 class="text-3xl">
  <%= @post.title %>
</h1>
<p>
  <%= @post.body %>
</p>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar bg-dark-subtle navbar-expand-lg">
    <div class="container-fluid">
      <%= link_to "Blog", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav ms-auto mb-2 mb-lg-0 gap-2">
          <% if user_signed_in? %>
            <div class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: 'delete' }, class: "btn btn-sm btn-link" %>
            </div>
            <div class="nav-item">
              <%= link_to "My Profile", profile_path, class: 'btn btn-sm btn-link' %>
            </div>
            <div class="nav-item">
              <%= link_to "Create", new_post_path, class: "btn btn-sm btn-primary" %>
            </div>
          <% else %>
            <div class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-sm btn-primary" %>
            </div>
            <div class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "btn btn-sm btn-secondary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_header.html.haml
%header#main-header
  .logo Logo
  %nav
    %a.secondary{href: root_url} Home
    %a.secondary{href: root_url} My Profile
    %a.secondary{href: root_url} contact
    %a.secondary{href: root_url} My Profile
    %a{href: root_url} Sign in
    %a{href: root_url} Sign up
    %a{href: root_url} My account
    %a{href: root_url} Log out

app/views/layouts/_messages.html.erb
<div class="container mt-5 mb-3">
  <% if notice.present? %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>

  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= content_for(:title) || "Blog" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <link rel="manifest" href="/manifest.json">
  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body class="bg-body-secondary">
<%= render "layouts/header" %>
<main>
  <%= render "layouts/messages" %>
  <%= yield %>
</main>
</body>
</html>

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html{lang: "sr"}
  %head
    %title= content_for(:title) || "Blog App"
    %meta{content: "width=device-width,initial-scale=1", name: "viewport"}
    %meta{content: "yes", name: "apple-mobile-web-app-capable"}
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    %link{href: "/manifest.json", rel: "manifest"}
    %link{href: "/icon.png", rel: "icon", type: "image/png"}
    %link{href: "/icon.svg", rel: "icon", type: "image/svg+xml"}
    %link{href: "/icon.png", rel: "apple-touch-icon"}

    // Fonts
    %link{rel: "preconnect", href: "https://fonts.googleapis.com"}
    %link{rel: "preconnect", href: "https://fonts.gstatic.com", crossorigin: true}
    %link{href: "https://fonts.googleapis.com/css2?family=Aleo:ital,wght@0,100..900;1,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap", rel: "stylesheet"}

    // Main styles
    = stylesheet_link_tag "application", "data-turbo-track": "reload"

    // JS
    = javascript_importmap_tags

  %body
    = render "layouts/header"
    %main
    = yield

app/views/layouts/errors.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= content_for(:title) || 'Error' %></title>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<div class="d-flex align-items-center justify-content-center flex-column" style="height: 100dvh">
  <%= yield %>
</div>
</body>
</html>

app/views/pages/home.html.haml
.container
  %section
    .section-inner
      %h2.section-title Recent posts
      %p.section-subtitle Hello World
      .flex.flex-col.gap-5
        = render "partials/blog-card"
        = render "partials/blog-card"
        = render "partials/blog-card"

app/views/pages/profile.html.erb
<section class="container mt-5">
  <div class="d-flex justify-content-between align-items-center">
    <h1>Hello <%= @user.username %></h1>
    <%= link_to "Edit profile", edit_user_registration_path, class: 'btn btn-primary' %>
  </div>
  <hr>
  <div class="row row-cols-3 row-gap-3">
    <% if @posts.any? %>
      <% @posts.each do |post| %>
        <div class="col">
          <%= render post %>
        </div>
      <% end %>
    <% else %>
      <p>You don't have any posts yet.</p>
    <% end %>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @posts %>
  </div>
</section>

app/views/partials/_blog-card.html.haml
%article.card
  %img.card-thumbnail{ src: "https://via.placeholder.com/300x200", alt: "Placeholder image" }
  .card-content
    %h3.card-title Card title
    %p.card-description Card description
    %a.secondary{ href: "#" } Read more

app/views/posts/_comment-card.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
  <article class="card mb-3">
    <div class="card-body">
      <% if notice.present? %>
        <p class="alert alert-success p-2 m-0 mb-2"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger p-2 m-0 mb-2"><%= alert %></p>
      <% end %>
      <p class="card-text"><%= comment.body %></p>
      <p class="card-text">
        <small class="text-muted">
          by <%= comment.user.present? ? comment.user.username : "(deleted)" %>
        </small>
      </p>
    </div>
    <% if comment.user == current_user %>
      <div class="card-footer d-flex gap-2">
        <button
          class="btn btn-sm btn-primary"
          data-controller="comment"
          data-action="click->comment#edit"
          data-path="<%= edit_post_comment_path(@post, comment) %>"
        >
          Edit
        </button>
        <%= button_to "Delete", [@post, comment], method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
      </div>
    <% end %>
  </article>
<% end %>

app/views/posts/_comment-edit-form.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
  <%= form_with model: [@post, comment], class: 'card' do |form| %>
    <div class="card-body">
      <% if alert.present? %>
        <p class="alert alert-danger p-2 m-0 mb-2"><%= alert %></p>
      <% end %>
      <div class="mb-3">
        <%= form.text_area :body, rows: 3, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, rows: 25, class: "form-control" %>
  </div>

  <div class="d-flex gap-3 mb-3">
    <%= form.submit class: "btn btn-success" %>
    <%= link_to "Back to all posts", posts_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="card h-100" id="<%= dom_id post %>">
  <div class="card-body d-flex flex-column">
    <h5 class="card-title"><%= post.title %></h5>
    <p class="card-text"><%= truncate(post.body, length: 100) %></p>
    <div class="d-flex gap-2 mt-auto">
      <% if post.user == current_user %>
        <%= link_to "Edit", edit_post_path(post), class: 'btn btn-outline-primary' %>
        <%= button_to "Delete", post_path(post), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %>
      <% end %>
      <%= link_to "View", post_path(post), class: 'btn btn-outline-primary' %>
    </div>
  </div>
  <div class="card-footer d-flex justify-content-between align-items-center">
    <time><%= post.created_at.strftime("%d %B, %Y") %></time>
    <p class="m-0">by <%= post.user.username %></p>
  </div>
</article>

app/views/posts/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
  <article class="card mb-3">
    <div class="card-body">
      <p class="card-text"><%= comment.body %></p>
      <p class="card-text">
        <small class="text-muted">
          by <%= comment.user.present? ? comment.user.username : "(deleted)" %>
        </small>
      </p>
    </div>
    <% if comment.user == current_user %>
      <div class="card-footer d-flex gap-2">
        <button
          class="btn btn-sm btn-primary"
          data-controller="comment"
          data-action="click->comment#edit"
          data-path="<%= edit_post_comment_path(@post, comment) %>"
        >
          Edit
        </button>
        <%= button_to "Delete", [@post, comment], method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
      </div>
    <% end %>
  </article>
<% end %>

app/views/posts/comments/_edit-form.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
  <%= form_with model: [@post, comment], class: 'card' do |form| %>
    <div class="card-body">
      <% if comment.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <ul class="mb-0">
            <% comment.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="mb-3">
        <%= form.text_area :body, rows: 3, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.submit "Save", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/posts/comments/_form.html.erb
<%= form_with(model: [@post, @post.comments.build]) do |form| %>
  <% if flash[:new_comment_errors] %>
    <div id="error_explanation_2" class="alert alert-danger">
      <ul class="mb-0">
        <% flash[:new_comment_errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :body, "Comment", class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>
  <%= form.submit "Add comment", class: 'btn btn-primary' %>
<% end %>

app/views/posts/comments/_list.html.erb
<h2>Comments</h2>
<hr>
<% if @comments.any? %>
  <% @comments.each do |comment| %>
    <%= render "posts/comments/comment", comment: comment %>
  <% end %>
  <nav class="d-flex justify-content-center">
    <ul class="pagination pagination-sm">
      <li class="page-item">
        <%= link_to_prev_page @comments, '<', class: 'page-link' %>
      </li>
      <li class="page-item">
        <%= link_to_next_page @comments, '>', class: 'page-link' %>
      </li>
    </ul>
  </nav>
<% else %>
  <p class="text-muted">No comments yet.</p>
<% end %>
<hr>
<% if user_signed_in? %>
  <h2>Add a comment</h2>
  <%= render "posts/comments/form" %>
<% else %>
  <p>
    You need to <%= link_to "Sign in", new_user_session_path %> to add a comment.
  </p>
<% end %>

app/views/posts/edit.html.erb
<div class="container mt-5">
  <h1 class="font-bold text-4xl">Editing post</h1>
  <hr>
  <%= render "form", post: @post %>
</div>

app/views/posts/index.html.erb
<% content_for :title, "Posts" %>

<div class="container mt-5">
  <h1>Posts</h1>
  <hr>
  <div id="posts" class="row row-cols-3 row-gap-3">
    <% if @posts.any? %>
      <% @posts.each do |post| %>
        <div class="col">
          <%= render post %>
        </div>
      <% end %>
    <% else %>
      <p>There are no posts available.</p>
    <% end %>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container mt-5">
  <h1 class="font-bold text-4xl">New post</h1>
  <hr>
  <%= render "form", post: @post %>
</div>

app/views/posts/show.html.erb
<section class="container mt-5">
  <div class="row">
    <div class="col">
      <h1>
        <%= @post.title %>
        <small class="text-body-secondary">
          by <%= @post.user.username %>
        </small>
      </h1>

      <p><%= md_to_html @post.body %></p>

      <div class="d-flex gap-2">
        <%= link_to "Back", posts_path, class: "btn btn-secondary" %>
        <% if @post.user == current_user %>
          <%= link_to "Edit", edit_post_path(@post), class: "btn btn-primary" %>
          <%= button_to "Delete", @post, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
    <div class="col-4">
      <%= render "posts/comments/list" %>
    </div>
  </div>
</section>